# -*- coding: utf-8 -*-
"""QR Code Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lF-hbPIF9Bq3C7Y_hKxTdA24bbTYJCaL
"""

!apt-get update
!apt-get install -y libzbar0
!pip install pyzbar

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from pyzbar.pyzbar import decode

# Get the uploaded file name
image_file = list(uploaded.keys())[0]

# Read the image file
img = cv2.imread(image_file)

# Decode the barcodes in the image
for barcode in decode(img):
    myData = barcode.data.decode('utf-8')
    print(myData)

    # Draw a polygon around the barcode
    pts = np.array([barcode.polygon], np.int32)
    pts = pts.reshape((-1, 1, 2))
    cv2.polylines(img, [pts], True, (255, 0, 255), 5)

    # Display the decoded data on the image
    pts2 = barcode.rect
    cv2.putText(img, myData, (pts2[0], pts2[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 255), 2)

# Display the result
from google.colab.patches import cv2_imshow
cv2_imshow(img)

# Save the processed image (optional)
cv2.imwrite("processed_image.jpg", img)